"use strict";
const FILES="abcdefghijklmn";
const SYM={white:{king:"♔",queen:"♕",rook:"♖",bishop:"♗",knight:"♘",pawn:"♙"},black:{king:"♚",queen:"♛",rook:"♜",bishop:"♝",knight:"♞",pawn:"♟"}};
const SP={wizard:"🧙",archer:"🏹",dragon:"🐉",guardian:"🛡️"};
const LETTER={king:"K",queen:"Q",rook:"R",bishop:"B",knight:"N",pawn:"",wizard:"M",archer:"A",dragon:"D",guardian:"G"};
const VAL={pawn:1,knight:3,bishop:3,rook:5,queen:9,wizard:4,archer:4,guardian:5,dragon:7,king:0};
const $=id=>document.getElementById(id);
let S={mode:"classic",cols:8,board:[],turn:"white",selected:null,legal:[],history:[],undo:[],captured:[],last:null,ep:null,half:0,counts:{},over:false,flipped:false,time:600,clock:{white:600,black:600},timer:null,events:{},climate:null,climateLeft:0,climateEnabled:true,pending:null};
function piece(type,color){return {type,color,hasMoved:false};}
function clone(v){return JSON.parse(JSON.stringify(v));}
function backRank(mode){return mode==="special"?["dragon","wizard","archer","guardian","rook","knight","bishop","queen","king","bishop","knight","rook","guardian","archer","wizard","dragon"]:["rook","knight","bishop","queen","king","bishop","knight","rook"]}
function init(){S.cols=S.mode==="special"?16:8;S.board=Array.from({length:8},()=>Array(S.cols).fill(null));let b=backRank(S.mode);for(let c=0;c<S.cols;c++){S.board[0][c]=piece(b[c],"black");S.board[1][c]=piece("pawn","black");S.board[6][c]=piece("pawn","white");S.board[7][c]=piece(b[c],"white")}S.turn="white";S.selected=null;S.legal=[];S.history=[];S.undo=[];S.captured=[];S.last=null;S.ep=null;S.half=0;S.counts={};S.over=false;S.events=S.mode==="special"&&S.climateEnabled?makeEvents():{};S.climate=null;S.climateLeft=0;S.clock={white:S.time,black:S.time};recordPos();render();startTimer();}
function makeEvents(){let e={};let add=(r,c,t,p)=>e[r+","+c]={type:t,pair:p,used:false};let a=Math.floor(S.cols*.32),b=S.cols-1-a;add(3,a,"portal","4,"+b);add(4,b,"portal","3,"+a);add(3,Math.floor(S.cols/2)-2,"well");add(4,Math.floor(S.cols/2)+1,"well");add(3,Math.floor(S.cols/2)+2,"trap");add(4,Math.floor(S.cols/2)-3,"trap");return e;}
function rcKey(r,c){return r+","+c}function inB(r,c){return r>=0&&r<8&&c>=0&&c<S.cols}function enemy(a,b){return a&&b&&a.color!==b.color}
function dirs(type){if(type==="bishop")return [[1,1],[1,-1],[-1,1],[-1,-1]];if(type==="rook")return [[1,0],[-1,0],[0,1],[0,-1]];if(type==="queen")return [...dirs("bishop"),...dirs("rook")];if(type==="wizard")return dirs("bishop");if(type==="dragon")return dirs("bishop");return []}
function ray(r,c,p,ds,moves){for(const[dR,dC]of ds){let nr=r+dR,nc=c+dC;while(inB(nr,nc)){let q=S.board[nr][nc];if(!q)moves.push({r:nr,c:nc});else{if(enemy(p,q))moves.push({r:nr,c:nc,capture:true});break}nr+=dR;nc+=dC}}}
function pseudo(r,c,attack=false){let p=S.board[r][c];if(!p)return [];let m=[],dir=p.color==="white"?-1:1;if(p.type==="pawn"){if(attack){for(let dc of[-1,1])if(inB(r+dir,c+dc))m.push({r:r+dir,c:c+dc});return m}if(inB(r+dir,c)&&!S.board[r+dir][c]){m.push({r:r+dir,c});let start=p.color==="white"?6:1;if(r===start&&!S.board[r+2*dir][c])m.push({r:r+2*dir,c})}for(let dc of[-1,1]){let nr=r+dir,nc=c+dc;if(inB(nr,nc)&&enemy(p,S.board[nr][nc]))m.push({r:nr,c:nc,capture:true});if(S.ep&&S.ep.r===nr&&S.ep.c===nc)m.push({r:nr,c:nc,ep:true,capture:true})}}
else if(["bishop","rook","queen","wizard","dragon"].includes(p.type)){ray(r,c,p,dirs(p.type),m);if(p.type==="wizard"){for(const[dR,dC]of dirs("rook")){let nr=r+dR,nc=c+dC;if(inB(nr,nc)&&(!S.board[nr][nc]||enemy(p,S.board[nr][nc])))m.push({r:nr,c:nc,capture:!!S.board[nr][nc]})}}if(p.type==="dragon"){for(const[dR,dC]of [[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]]){let nr=r+dR,nc=c+dC;if(inB(nr,nc)&&(!S.board[nr][nc]||enemy(p,S.board[nr][nc])))m.push({r:nr,c:nc,capture:!!S.board[nr][nc]})}}}
else if(p.type==="knight"){for(const[dR,dC]of [[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]]){let nr=r+dR,nc=c+dC;if(inB(nr,nc)&&(!S.board[nr][nc]||enemy(p,S.board[nr][nc])))m.push({r:nr,c:nc,capture:!!S.board[nr][nc]})}}
else if(p.type==="king"||p.type==="archer"||p.type==="guardian"){for(let dR=-1;dR<=1;dR++)for(let dC=-1;dC<=1;dC++){if(!dR&&!dC)continue;let nr=r+dR,nc=c+dC;if(inB(nr,nc)&&(!S.board[nr][nc]||enemy(p,S.board[nr][nc]))){if(p.type!=="archer"||!S.board[nr][nc])m.push({r:nr,c:nc,capture:!!S.board[nr][nc]})}}
if(p.type==="archer"&&!attack){for(const[dR,dC]of [[2,0],[-2,0],[0,2],[0,-2]]){let nr=r+dR,nc=c+dC,mr=r+dR/2,mc=c+dC/2;if(inB(nr,nc)&&S.board[nr][nc]&&enemy(p,S.board[nr][nc])&&!S.board[mr][mc])m.push({r:nr,c:nc,shot:true,capture:true})}}
if(p.type==="guardian"&&!attack){for(const[dR,dC]of [[2,0],[-2,0],[0,2],[0,-2]]){let nr=r+dR,nc=c+dC;if(inB(nr,nc)&&!S.board[nr][nc])m.push({r:nr,c:nc})}}
if(p.type==="king"&&!attack&&!p.hasMoved){let home=p.color==="white"?7:0;for(const side of [-1,1]){let rookCol=side===-1?findRook(home,-1):findRook(home,1);if(rookCol!==null){let clear=true;for(let cc=Math.min(c,rookCol)+1;cc<Math.max(c,rookCol);cc++)if(S.board[home][cc])clear=false;if(clear&&!isCheck(p.color)&&!attacked(home,c+side,p.color)&&!attacked(home,c+2*side,p.color))m.push({r:home,c:c+2*side,castle:true,rookCol})}}}
}return m;}
function findRook(r,side){let king=S.board[r].findIndex(x=>x&&x.type==="king"&&x.color===S.board[r][S.board[r].findIndex(y=>y&&y.type==="king")].color);let p=S.board[r][king];for(let c=king+side;c>=0&&c<S.cols;c+=side){let q=S.board[r][c];if(q){if(q.type==="rook"&&q.color===p.color&&!q.hasMoved)return c;return null}}return null}
function attacked(r,c,byColor){for(let rr=0;rr<8;rr++)for(let cc=0;cc<S.cols;cc++){let p=S.board[rr][cc];if(p&&p.color===byColor){let a=pseudo(rr,cc,true);if(a.some(x=>x.r===r&&x.c===c))return true}}return false}
function kingPos(color){for(let r=0;r<8;r++)for(let c=0;c<S.cols;c++){let p=S.board[r][c];if(p&&p.type==="king"&&p.color===color)return {r,c}}return null}
function isCheck(color){let k=kingPos(color);return k?attacked(k.r,k.c,color==="white"?"black":"white"):true}
function legalMoves(r,c){let p=S.board[r][c];if(!p||p.color!==S.turn)return[];return pseudo(r,c).filter(m=>{let snap=snapshot();applyMove(r,c,m,true);let ok=!isCheck(p.color);restore(snap);return ok})}
function snapshot(){return clone({board:S.board,turn:S.turn,selected:S.selected,legal:S.legal,history:S.history,captured:S.captured,last:S.last,ep:S.ep,half:S.half,counts:S.counts,events:S.events,climate:S.climate,climateLeft:S.climateLeft,clock:S.clock,over:S.over})}function restore(x){Object.assign(S,x)}
function applyMove(r,c,m,silent=false){let p=S.board[r][c],target=S.board[m.r][m.c],capture=target;if(m.shot){S.board[m.r][m.c]=null;S.captured.push({type:target.type,color:target.color});S.half=0;return}if(m.ep){let cr=r,cc=m.c;capture=S.board[cr][cc];S.board[cr][cc]=null}S.board[m.r][m.c]=p;S.board[r][c]=null;if(capture)S.captured.push({type:capture.type,color:capture.color});if(m.castle){let side=m.c>c?1:-1;let rook=S.board[r][m.rookCol];S.board[r][m.rookCol]=null;S.board[r][m.c-side]=rook;rook.hasMoved=true}p.hasMoved=true;S.ep=null;if(p.type==="pawn"&&Math.abs(m.r-r)===2)S.ep={r:(r+m.r)/2,c};S.half=(p.type==="pawn"||capture)?0:S.half+1;if(!silent&&S.mode==="special")triggerEvents(m.r,m.c,p);}
function triggerEvents(r,c,p){let e=S.events[rcKey(r,c)];if(e&&!e.used){if(e.type==="portal"&&e.pair){let [pr,pc]=e.pair.split(",").map(Number);if(!S.board[pr][pc]){S.board[pr][pc]=S.board[r][c];S.board[r][c]=null;r=pr;c=pc;msg("🌀 Portal ativado!")}e.used=true}if(e.type==="well"&&p.type==="pawn"){p.type="queen";e.used=true;msg("💎 Poço promoveu o peão!")}if(e.type==="trap"&&p.type!=="king"){S.board[r][c]=null;e.used=true;msg("🔥 Armadilha destruiu a peça!")}}if(S.climate&&S.climateLeft>0){S.climateLeft--;if(S.climateLeft===0){S.climate=null;msg("O clima voltou ao normal.")}}else if(Math.random()<0.18&&S.climateEnabled){let arr=["storm","snow","eclipse","quake"];S.climate=arr[Math.floor(Math.random()*arr.length)];S.climateLeft=4;msg({storm:"🌩 Tempestade: atmosfera intensa",snow:"❄ Nevasca: tabuleiro congelado",eclipse:"🌑 Eclipse: visibilidade reduzida",quake:"🌋 Terremoto: as peças estremecem"}[S.climate])}}
function san(r,c,m,before){let p=before.board[r][c],cap=m.capture?"x":"",to=FILES[m.c]+(8-m.r);if(m.castle)return m.c>c?"O-O":"O-O-O";if(m.shot)return "A"+FILES[c]+(8-r)+"»"+to;let s=LETTER[p.type];if(p.type==="pawn"&&m.capture)s=FILES[c];s+=cap+to;if(p.type==="pawn"&&(m.r===0||m.r===7))s+="=Q";return s}
function commit(r,c,m){if(S.over)return;let before=snapshot();let notation=san(r,c,m,before);S.undo.push(before);applyMove(r,c,m);let p=S.board[m.r][m.c];if(p&&p.type==="pawn"&&(m.r===0||m.r===7)){S.pending={r:m.r,c:m.c,color:p.color,notation};showPromotion();return}finishTurn(notation)}
function finishTurn(notation){S.history.push(notation);S.last={from:S.undo[S.undo.length-1]?null:null};S.lastMove=notation;S.turn=S.turn==="white"?"black":"white";recordPos();checkEnd();render();}
function showPromotion(){let box=$("promotionChoices");box.innerHTML="";for(let t of ["queen","rook","bishop","knight"]){let b=document.createElement("button");b.className="choice";b.textContent=SYM[S.pending.color][t];b.onclick=()=>{S.board[S.pending.r][S.pending.c].type=t;$("promotion").classList.add("hidden");finishTurn(S.pending.notation.replace("=Q","="+LETTER[t]));S.pending=null};box.appendChild(b)}$("promotion").classList.remove("hidden")}
function recordPos(){let k=S.board.map(row=>row.map(p=>p?`${p.color[0]}${p.type[0]}`:".").join("/")).join("|")+"|"+S.turn;S.counts[k]=(S.counts[k]||0)+1}
function insufficient(){let a=[];for(let row of S.board)for(let p of row)if(p&&p.type!=="king")a.push(p.type);return a.length===0||a.every(x=>["bishop","knight"].includes(x))&&a.length<=2}
function checkEnd(){if(S.half>=100){end("Empate pela regra dos 50 lances.");return}if(Object.values(S.counts).some(v=>v>=3)){end("Empate por repetição tripla.");return}if(insufficient()){end("Empate por material insuficiente.");return}let moves=allLegal(S.turn);if(!moves.length){if(isCheck(S.turn))end("Xeque-mate! "+(S.turn==="white"?"Pretas":"Brancas")+" vencem.");else end("Empate por afogamento.")}}
function allLegal(color){let old=S.turn;S.turn=color;let out=[];for(let r=0;r<8;r++)for(let c=0;c<S.cols;c++)if(S.board[r][c]?.color===color)out.push(...legalMoves(r,c));S.turn=old;return out}
function end(t){S.over=true;msg(t);stopTimer();}
function msg(t){$("message").textContent=t}
function render(){document.body.className="theme-"+$("theme").value+(S.climate?" climate-"+S.climate:"");$("gameView").classList.toggle("hidden",!S.board.length);$("modeLabel").textContent=S.mode==="classic"?"Clássico":"Especial";$("status").textContent=S.over?"Partida encerrada":`Vez das ${S.turn==="white"?"Brancas":"Pretas"}`;$("turnLabel").textContent=Math.floor(S.history.length/2)+1;$("climate").textContent=S.climate?`${S.climate.toUpperCase()} · ${S.climateLeft} lances`:"Nenhum evento ativo";renderCoords();let b=$("board");b.style.gridTemplateColumns=`repeat(${S.cols},1fr)`;b.innerHTML="";let rows=[...Array(8).keys()],cols=[...Array(S.cols).keys()];if(S.flipped){rows.reverse();cols.reverse()}for(let r of rows)for(let c of cols){let el=document.createElement("div");el.className="sq "+((r+c)%2?"dark":"light");el.tabIndex=0;el.dataset.r=r;el.dataset.c=c;if(S.selected&&S.selected.r===r&&S.selected.c===c)el.classList.add("sel");if(S.legal.some(m=>m.r===r&&m.c===c))el.classList.add(S.legal.find(m=>m.r===r&&m.c===c).capture?"capture":"legal");if(S.last&&((S.last.from?.r===r&&S.last.from?.c===c)||(S.last.to?.r===r&&S.last.to?.c===c)))el.classList.add("last");let p=S.board[r][c];if(p){let span=document.createElement("span");span.className="piece "+(p.color==="white"?"white-piece":"black-piece")+(SP[p.type]?" special "+p.type:"");span.textContent=SP[p.type]||SYM[p.color][p.type];el.appendChild(span)}let e=S.events[rcKey(r,c)];if(e&&!e.used){let z=document.createElement("span");z.className="event";z.textContent=e.type==="portal"?"🌀":e.type==="well"?"💎":"🔥";el.appendChild(z)}let kp=kingPos(S.turn);if(kp&&kp.r===r&&kp.c===c&&isCheck(S.turn))el.classList.add("check");el.onclick=()=>clickSquare(r,c);el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();clickSquare(r,c)}};b.appendChild(el)}renderHistory();renderCaptured();renderClock();}
function renderCoords(){let files=[...FILES.slice(0,S.cols)];let ranks=[8,7,6,5,4,3,2,1];if(S.flipped){files.reverse();ranks.reverse()}$("filesTop").style.gridTemplateColumns=`repeat(${S.cols},1fr)`;$("filesBottom").style.gridTemplateColumns=`repeat(${S.cols},1fr)`;$("filesTop").innerHTML=files.map(x=>`<span>${x}</span>`).join("");$("filesBottom").innerHTML=files.map(x=>`<span>${x}</span>`).join("");$("ranksLeft").innerHTML=ranks.map(x=>`<span>${x}</span>`).join("");$("ranksRight").innerHTML=ranks.map(x=>`<span>${x}</span>`).join("")}
function renderHistory(){let m=$("moves");m.innerHTML="";for(let i=0;i<S.history.length;i+=2){let d=document.createElement("div");d.className="move-row";d.innerHTML=`<span>${i/2+1}.</span><span>${S.history[i]||""}</span><span>${S.history[i+1]||""}</span>`;m.appendChild(d)}m.scrollTop=m.scrollHeight}
function renderCaptured(){let w=S.captured.filter(x=>x.color==="black").map(x=>SP[x.type]||SYM.black[x.type]).join(" ");let b=S.captured.filter(x=>x.color==="white").map(x=>SP[x.type]||SYM.white[x.type]).join(" ");$("capWhite").textContent=w;$("capBlack").textContent=b}
function clickSquare(r,c){if(S.over)return;let p=S.board[r][c];if(S.selected){let m=S.legal.find(x=>x.r===r&&x.c===c);if(m){let sr=S.selected.r,sc=S.selected.c;S.selected=null;S.legal=[];commit(sr,sc,m);return}if(p&&p.color===S.turn){S.selected={r,c};S.legal=legalMoves(r,c)}else{S.selected=null;S.legal=[]}}else if(p&&p.color===S.turn){S.selected={r,c};S.legal=legalMoves(r,c)}render()}
function startTimer(){stopTimer();if(!S.time)return;S.timer=setInterval(()=>{if(S.over)return;S.clock[S.turn]--;if(S.clock[S.turn]<=0){S.clock[S.turn]=0;end(`Tempo esgotado! ${S.turn==="white"?"Pretas":"Brancas"} vencem.`)}renderClock()},1000)}function stopTimer(){if(S.timer)clearInterval(S.timer);S.timer=null}function fmt(v){let m=Math.floor(v/60),s=v%60;return String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}function renderClock(){$("whiteClock").textContent=fmt(S.clock.white);$("blackClock").textContent=fmt(S.clock.black)}
function save(){localStorage.setItem("xadrez2-save",JSON.stringify({S}));msg("Partida salva com sucesso.")}function load(){let x=localStorage.getItem("xadrez2-save");if(!x){msg("Nenhum salvamento encontrado.");return}let d=JSON.parse(x).S;stopTimer();Object.assign(S,d);render();startTimer();msg("Partida restaurada.")}
function undo(){if(!S.undo.length||S.over)return;let x=S.undo.pop();restore(x);render();msg("Último lance desfeito.")}
function exportPGN(){let out=[];for(let i=0;i<S.history.length;i+=2)out.push(`${i/2+1}. ${S.history[i]||""}${S.history[i+1]?" "+S.history[i+1]:""}`);let blob=new Blob([out.join("\n")],{type:"text/plain"});let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="xadrez2.pgn";a.click();URL.revokeObjectURL(a.href)}
function confirm(title,text,cb){$("dialogTitle").textContent=title;$("dialogText").textContent=text;$("dialog").classList.remove("hidden");$("dialogOk").onclick=()=>{$("dialog").classList.add("hidden");cb()};$("dialogCancel").onclick=()=>$("dialog").classList.add("hidden")}
$("startBtn").onclick=()=>{S.mode=$("mode").value;S.time=Number($("time").value);S.climateEnabled=$("events").value==="on";$("setup").classList.add("hidden");$("gameView").classList.remove("hidden");init()};$("newBtn").onclick=()=>{stopTimer();$("gameView").classList.add("hidden");$("setup").classList.remove("hidden")};$("flipBtn").onclick=()=>{S.flipped=!S.flipped;render()};$("saveBtn").onclick=save;$("loadBtn").onclick=load;$("undoBtn").onclick=undo;$("exportBtn").onclick=exportPGN;$("drawBtn").onclick=()=>confirm("Oferecer empate","Ambos os jogadores concordam com o empate?",()=>end("Empate por acordo entre os jogadores."));$("resignBtn").onclick=()=>confirm("Desistir","Confirmar desistência?",()=>end(`Desistência! ${S.turn==="white"?"Pretas":"Brancas"} vencem.`));$("theme").onchange=render;
